/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 bg.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import {Regid}
export function Model(props) {
  const { nodes, materials } = useGLTF("/bg.gltf");
  return (
    
    <group {...props} dispose={null}>
      <group position={[-2.328, 1.83, 0.23]}>
        <group position={[0.007, 0.114, -0.008]} rotation={[1.571, 0, -1.571]}>
          <mesh
            geometry={nodes.Cube003_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube003_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.139, 0.117, 0.001]}
          rotation={[1.571, 0.275, -1.572]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube003_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube003_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.266, 0.116, 0.002]}
          rotation={[1.573, 0.31, -1.575]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube003_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube003_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group position={[0.023, 0.119, 0]} rotation={[1.582, 0.003, -1.57]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.175, 0.121, -0.002]}
          rotation={[1.573, 0.297, -1.577]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.282, 0.121, 0.006]}
          rotation={[1.572, 0.311, -1.576]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.045, 0.088, 0.022]}
          rotation={[1.571, 0.059, -1.568]}
        >
          <mesh
            geometry={nodes.Cube007_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube007_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.166, 0.09, 0.004]}
          rotation={[1.572, 0.293, -1.573]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube007_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube007_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.319, 0.088, 0.01]}
          rotation={[1.572, 0.393, -1.576]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube007_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube007_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.113, 0.099, 0.019]}
          rotation={[1.571, 0.272, -1.574]}
        >
          <mesh
            geometry={nodes.Cube008_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube008_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.237, 0.103, -0.004]}
          rotation={[1.573, 0.301, -1.577]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube008_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube008_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.378, 0.099, 0.011]}
          rotation={[1.574, 0.443, -1.578]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube008_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube008_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.094, 0.114, 0.008]}
          rotation={[1.572, 0.268, -1.573]}
        >
          <mesh
            geometry={nodes.Cube009_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube009_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.217, 0.119, 0.004]}
          rotation={[1.571, 0.298, -1.576]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube009_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube009_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.355, 0.113, 0.002]}
          rotation={[1.577, 0.442, -1.579]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube009_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube009_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.078, 0.114, 0.003]}
          rotation={[1.571, 0.268, -1.574]}
        >
          <mesh
            geometry={nodes.Cube010_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube010_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.199, 0.118, 0.004]}
          rotation={[1.572, 0.299, -1.576]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube010_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube010_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.336, 0.114, 0.002]}
          rotation={[1.574, 0.44, -1.577]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube010_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube010_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.131, 0.097, 0.003]}
          rotation={[1.571, 0.275, -1.572]}
        >
          <mesh
            geometry={nodes.Cube011_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube011_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.256, 0.101, 0.003]}
          rotation={[1.572, 0.308, -1.576]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube011_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube011_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.402, 0.095, 0.011]}
          rotation={[1.568, 0.467, -1.575]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube011_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube011_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
      </group>
      <group position={[-0.785, 0.972, 0.253]} rotation={[Math.PI, 0, Math.PI]}>
        <group
          position={[0.266, 0.116, 0.002]}
          rotation={[1.573, 0.31, -1.575]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube003_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube003_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.139, 0.117, 0.001]}
          rotation={[1.571, 0.275, -1.572]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube003_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube003_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group position={[0.007, 0.114, -0.008]} rotation={[1.571, 0, -1.571]}>
          <mesh
            geometry={nodes.Cube003_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube003_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.282, 0.121, 0.006]}
          rotation={[1.572, 0.311, -1.576]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.175, 0.121, -0.002]}
          rotation={[1.573, 0.297, -1.577]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group position={[0.023, 0.119, 0]} rotation={[1.582, 0.003, -1.57]}>
          <mesh
            geometry={nodes.Cube006_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube006_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.319, 0.088, 0.01]}
          rotation={[1.572, 0.393, -1.576]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube007_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube007_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.166, 0.09, 0.004]}
          rotation={[1.572, 0.293, -1.573]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube007_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube007_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.045, 0.088, 0.022]}
          rotation={[1.571, 0.059, -1.568]}
        >
          <mesh
            geometry={nodes.Cube007_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube007_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.378, 0.099, 0.011]}
          rotation={[1.574, 0.443, -1.578]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube008_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube008_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.237, 0.103, -0.004]}
          rotation={[1.573, 0.301, -1.577]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube008_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube008_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.113, 0.099, 0.019]}
          rotation={[1.571, 0.272, -1.574]}
        >
          <mesh
            geometry={nodes.Cube008_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube008_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.355, 0.113, 0.002]}
          rotation={[1.577, 0.442, -1.579]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube009_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube009_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.217, 0.119, 0.004]}
          rotation={[1.571, 0.298, -1.576]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube009_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube009_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.094, 0.114, 0.008]}
          rotation={[1.572, 0.268, -1.573]}
        >
          <mesh
            geometry={nodes.Cube009_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube009_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.336, 0.114, 0.002]}
          rotation={[1.574, 0.44, -1.577]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube010_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube010_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.199, 0.118, 0.004]}
          rotation={[1.572, 0.299, -1.576]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube010_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube010_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.078, 0.114, 0.003]}
          rotation={[1.571, 0.268, -1.574]}
        >
          <mesh
            geometry={nodes.Cube010_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube010_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.402, 0.095, 0.011]}
          rotation={[1.568, 0.467, -1.575]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube011_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube011_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.256, 0.101, 0.003]}
          rotation={[1.572, 0.308, -1.576]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube011_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube011_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
        <group
          position={[0.131, 0.097, 0.003]}
          rotation={[1.571, 0.275, -1.572]}
        >
          <mesh
            geometry={nodes.Cube011_1.geometry}
            material={materials["book cover"]}
          />
          <mesh
            geometry={nodes.Cube011_2.geometry}
            material={materials["stacked paper"]}
          />
        </group>
      </group>
      <group position={[-1.168, 1.83, 0.221]} rotation={[Math.PI, 0, Math.PI]}>
        <group
          position={[0.18, 0.097, 0.007]}
          rotation={[1.563, 0.425, -1.553]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube005_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube005_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.099, 0.101, -0.002]}
          rotation={[1.572, 0.319, -1.571]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube005_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube005_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group position={[0.043, 0.1, 0.006]} rotation={[1.571, 0.003, -1.572]}>
          <mesh
            geometry={nodes.Cube005_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube005_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.389, 0.112, 0.009]}
          rotation={[1.562, 0.482, -1.551]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube012_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube012_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.302, 0.114, 0.006]}
          rotation={[1.564, 0.444, -1.553]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube012_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube012_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.23, 0.109, 0.004]}
          rotation={[1.562, 0.431, -1.548]}
        >
          <mesh
            geometry={nodes.Cube012_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube012_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.421, 0.106, 0.003]}
          rotation={[1.579, 0.554, -1.559]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube013_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube013_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.322, 0.112, -0.001]}
          rotation={[1.565, 0.443, -1.553]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube013_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube013_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.249, 0.108, 0.007]}
          rotation={[1.571, 0.439, -1.555]}
        >
          <mesh
            geometry={nodes.Cube013_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube013_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.16, 0.1, 0.005]}
          rotation={[1.565, 0.418, -1.557]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube014_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube014_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.346, 0.098, -0.003]}
          rotation={[1.56, 0.461, -1.551]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube014_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube014_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group position={[0.027, 0.1, 0.017]} rotation={[1.571, 0.003, -1.57]}>
          <mesh
            geometry={nodes.Cube014_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube014_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.14, 0.088, -0.003]}
          rotation={[1.567, 0.372, -1.562]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube015_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube015_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.057, 0.091, 0.008]}
          rotation={[1.57, 0.005, -1.573]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube015_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube015_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.008, 0.087, 0.014]}
          rotation={[1.571, 0.003, -1.57]}
        >
          <mesh
            geometry={nodes.Cube015_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube015_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.362, 0.114, 0.007]}
          rotation={[1.558, 0.479, -1.55]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube016_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube016_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.277, 0.116, -0.002]}
          rotation={[1.566, 0.441, -1.555]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube016_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube016_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.206, 0.111, 0.001]}
          rotation={[1.563, 0.432, -1.552]}
        >
          <mesh
            geometry={nodes.Cube016_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube016_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.108, 0.116, -0.003]}
          rotation={[1.57, 0.318, -1.57]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube017_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube017_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.26, 0.111, 0.006]}
          rotation={[1.568, 0.439, -1.554]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube017_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube017_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.191, 0.107, 0.003]}
          rotation={[1.562, 0.429, -1.549]}
        >
          <mesh
            geometry={nodes.Cube017_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube017_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
      </group>
      <group position={[2.046, 1.424, 0.197]} rotation={[Math.PI, 0, Math.PI]}>
        <group position={[0.043, 0.1, 0.006]} rotation={[1.571, 0.003, -1.572]}>
          <mesh
            geometry={nodes.Cube005_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube005_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.099, 0.101, -0.002]}
          rotation={[1.572, 0.319, -1.571]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube005_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube005_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.18, 0.097, 0.007]}
          rotation={[1.563, 0.425, -1.553]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube005_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube005_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.23, 0.109, 0.004]}
          rotation={[1.562, 0.431, -1.548]}
        >
          <mesh
            geometry={nodes.Cube012_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube012_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.302, 0.114, 0.006]}
          rotation={[1.564, 0.444, -1.553]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube012_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube012_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.389, 0.112, 0.009]}
          rotation={[1.562, 0.482, -1.551]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube012_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube012_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.249, 0.108, 0.007]}
          rotation={[1.571, 0.439, -1.555]}
        >
          <mesh
            geometry={nodes.Cube013_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube013_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.322, 0.112, -0.001]}
          rotation={[1.565, 0.443, -1.553]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube013_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube013_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.421, 0.106, 0.003]}
          rotation={[1.579, 0.554, -1.559]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube013_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube013_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group position={[0.027, 0.1, 0.017]} rotation={[1.571, 0.003, -1.57]}>
          <mesh
            geometry={nodes.Cube014_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube014_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.346, 0.098, -0.003]}
          rotation={[1.56, 0.461, -1.551]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube014_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube014_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.16, 0.1, 0.005]}
          rotation={[1.565, 0.418, -1.557]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube014_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube014_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.008, 0.087, 0.014]}
          rotation={[1.571, 0.003, -1.57]}
        >
          <mesh
            geometry={nodes.Cube015_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube015_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.057, 0.091, 0.008]}
          rotation={[1.57, 0.005, -1.573]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube015_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube015_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.14, 0.088, -0.003]}
          rotation={[1.567, 0.372, -1.562]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube015_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube015_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.206, 0.111, 0.001]}
          rotation={[1.563, 0.432, -1.552]}
        >
          <mesh
            geometry={nodes.Cube016_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube016_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.277, 0.116, -0.002]}
          rotation={[1.566, 0.441, -1.555]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube016_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube016_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.362, 0.114, 0.007]}
          rotation={[1.558, 0.479, -1.55]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube016_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube016_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.191, 0.107, 0.003]}
          rotation={[1.562, 0.429, -1.549]}
        >
          <mesh
            geometry={nodes.Cube017_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube017_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.26, 0.111, 0.006]}
          rotation={[1.568, 0.439, -1.554]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube017_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube017_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
        <group
          position={[0.108, 0.116, -0.003]}
          rotation={[1.57, 0.318, -1.57]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube017_1.geometry}
            material={materials["book cover.001"]}
          />
          <mesh
            geometry={nodes.Cube017_2.geometry}
            material={materials["stacked paper.001"]}
          />
        </group>
      </group>
      <group position={[-0.301, 1.83, 0.218]}>
        <group position={[-0.237, 0.112, 0]} rotation={[1.57, -0.265, -1.574]}>
          <mesh
            geometry={nodes.Cube018_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube018_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.162, 0.118, 0.003]}
          rotation={[1.57, -0.208, -1.57]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube018_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube018_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.312, 0.114, 0.002]}
          rotation={[1.569, -0.358, -1.573]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube018_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube018_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.219, 0.117, -0.001]}
          rotation={[1.57, -0.264, -1.574]}
        >
          <mesh
            geometry={nodes.Cube019_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube019_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.144, 0.123, -0.003]}
          rotation={[1.571, -0.205, -1.569]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube019_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube019_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.066, 0.124, 0]}
          rotation={[1.572, -0.163, -1.564]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube019_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube019_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.438, 0.077, 0.014]}
          rotation={[1.577, -0.59, -1.569]}
        >
          <mesh
            geometry={nodes.Cube020_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube020_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.364, 0.085, 0.007]}
          rotation={[1.565, -0.462, -1.574]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube020_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube020_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.298, 0.09, 0]}
          rotation={[1.57, -0.3, -1.573]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube020_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube020_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.396, 0.093, 0.013]}
          rotation={[1.57, -0.473, -1.572]}
        >
          <mesh
            geometry={nodes.Cube021_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube021_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.093, 0.104, -0.006]}
          rotation={[1.572, -0.202, -1.566]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube021_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube021_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.271, 0.103, 0.008]}
          rotation={[1.571, -0.272, -1.573]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube021_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube021_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.174, 0.117, 0.006]}
          rotation={[1.569, -0.208, -1.574]}
        >
          <mesh
            geometry={nodes.Cube022_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube022_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.104, 0.122, -0.001]}
          rotation={[1.572, -0.202, -1.566]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube022_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube022_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.026, 0.123, -0.001]}
          rotation={[1.573, -0.162, -1.562]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube022_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube022_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.191, 0.114, 0.003]}
          rotation={[1.57, -0.209, -1.573]}
        >
          <mesh
            geometry={nodes.Cube023_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube023_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.122, 0.12, 0.001]}
          rotation={[1.57, -0.204, -1.567]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube023_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube023_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.044, 0.12, 0.001]}
          rotation={[1.572, -0.161, -1.562]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube023_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube023_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.379, 0.091, 0.003]}
          rotation={[1.569, -0.473, -1.572]}
        >
          <mesh
            geometry={nodes.Cube024_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube024_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.333, 0.1, 0.002]}
          rotation={[1.571, -0.36, -1.571]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube024_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube024_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
        <group
          position={[-0.253, 0.102, 0.008]}
          rotation={[1.57, -0.267, -1.574]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube024_1.geometry}
            material={materials["book cover.002"]}
          />
          <mesh
            geometry={nodes.Cube024_2.geometry}
            material={materials["stacked paper.002"]}
          />
        </group>
      </group>
      <group position={[-1.176, 1.83, 0.225]} rotation={[Math.PI, 0, Math.PI]}>
        <group
          position={[-0.044, 0.12, 0.006]}
          rotation={[1.573, -0.183, -1.563]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube028_1.geometry}
            material={materials["book cover.003"]}
          />
          <mesh
            geometry={nodes.Cube028_2.geometry}
            material={materials["stacked paper.003"]}
          />
        </group>
        <group
          position={[-0.134, 0.117, 0.008]}
          rotation={[1.573, -0.338, -1.564]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube028_1.geometry}
            material={materials["book cover.003"]}
          />
          <mesh
            geometry={nodes.Cube028_2.geometry}
            material={materials["stacked paper.003"]}
          />
        </group>
        <group
          position={[-0.026, 0.122, 0.005]}
          rotation={[1.572, -0.181, -1.562]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube029_1.geometry}
            material={materials["book cover.003"]}
          />
          <mesh
            geometry={nodes.Cube029_2.geometry}
            material={materials["stacked paper.003"]}
          />
        </group>
        <group
          position={[-0.116, 0.118, 0.003]}
          rotation={[1.571, -0.337, -1.564]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube029_1.geometry}
            material={materials["book cover.003"]}
          />
          <mesh
            geometry={nodes.Cube029_2.geometry}
            material={materials["stacked paper.003"]}
          />
        </group>
        <group
          position={[-0.204, 0.108, 0.011]}
          rotation={[1.573, -0.44, -1.564]}
        >
          <mesh
            geometry={nodes.Cube029_1.geometry}
            material={materials["book cover.003"]}
          />
          <mesh
            geometry={nodes.Cube029_2.geometry}
            material={materials["stacked paper.003"]}
          />
        </group>
        <group
          position={[-0.066, 0.123, 0.007]}
          rotation={[1.572, -0.184, -1.563]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube026_1.geometry}
            material={materials["book cover.003"]}
          />
          <mesh
            geometry={nodes.Cube026_2.geometry}
            material={materials["stacked paper.003"]}
          />
        </group>
        <group
          position={[-0.157, 0.12, 0.003]}
          rotation={[1.574, -0.339, -1.563]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube026_1.geometry}
            material={materials["book cover.003"]}
          />
          <mesh
            geometry={nodes.Cube026_2.geometry}
            material={materials["stacked paper.003"]}
          />
        </group>
        <group
          position={[-0.177, 0.115, 0.009]}
          rotation={[1.565, -0.343, -1.566]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube025_1.geometry}
            material={materials["book cover.003"]}
          />
          <mesh
            geometry={nodes.Cube025_2.geometry}
            material={materials["stacked paper.003"]}
          />
        </group>
        <group
          position={[-0.105, 0.102, -0.001]}
          rotation={[1.575, -0.323, -1.563]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube027_1.geometry}
            material={materials["book cover.003"]}
          />
          <mesh
            geometry={nodes.Cube027_2.geometry}
            material={materials["stacked paper.003"]}
          />
        </group>
      </group>
      <group position={[1.237, 0.9, 2.3]} rotation={[Math.PI, 0, Math.PI]}>
        <group position={[0, 0.047, -0.006]} rotation={[0.011, -0.194, 0.03]}>
          <mesh
            geometry={nodes.Cube031_1.geometry}
            material={materials["book cover.004"]}
          />
          <mesh
            geometry={nodes.Cube031_2.geometry}
            material={materials["stacked paper.004"]}
          />
        </group>
        <group
          position={[-0.012, 0.061, -0.007]}
          rotation={[0.001, 0.118, 0.026]}
        >
          <mesh
            geometry={nodes.Cube033_1.geometry}
            material={materials["book cover.004"]}
          />
          <mesh
            geometry={nodes.Cube033_2.geometry}
            material={materials["stacked paper.004"]}
          />
        </group>
        <group
          position={[0.013, 0.11, -0.008]}
          rotation={[-0.005, -0.002, 0.005]}
        >
          <mesh
            geometry={nodes.Cube030_1.geometry}
            material={materials["book cover.004"]}
          />
          <mesh
            geometry={nodes.Cube030_2.geometry}
            material={materials["stacked paper.004"]}
          />
        </group>
        <group
          position={[0.016, 0.005, -0.015]}
          rotation={[0.003, -0.103, 0.012]}
        >
          <mesh
            geometry={nodes.Cube032_1.geometry}
            material={materials["book cover.004"]}
          />
          <mesh
            geometry={nodes.Cube032_2.geometry}
            material={materials["stacked paper.004"]}
          />
        </group>
        <group
          position={[0.007, 0.035, -0.012]}
          rotation={[0.015, -0.3, 0.025]}
        >
          <mesh
            geometry={nodes.Cube034_1.geometry}
            material={materials["book cover.004"]}
          />
          <mesh
            geometry={nodes.Cube034_2.geometry}
            material={materials["stacked paper.004"]}
          />
        </group>
        <group
          position={[0.012, 0.022, -0.018]}
          rotation={[-0.001, 0.326, 0.011]}
        >
          <mesh
            geometry={nodes.Cube035_1.geometry}
            material={materials["book cover.004"]}
          />
          <mesh
            geometry={nodes.Cube035_2.geometry}
            material={materials["stacked paper.004"]}
          />
        </group>
        <group
          position={[-0.02, 0.098, -0.007]}
          rotation={[-0.004, -0.009, 0.008]}
        >
          <mesh
            geometry={nodes.Cube036_1.geometry}
            material={materials["book cover.004"]}
          />
          <mesh
            geometry={nodes.Cube036_2.geometry}
            material={materials["stacked paper.004"]}
          />
        </group>
        <group
          position={[-0.017, 0.078, -0.006]}
          rotation={[0.005, -0.189, 0.02]}
        >
          <mesh
            geometry={nodes.Cube037_1.geometry}
            material={materials["book cover.004"]}
          />
          <mesh
            geometry={nodes.Cube037_2.geometry}
            material={materials["stacked paper.004"]}
          />
        </group>
      </group>
      <group position={[1.004, 0.9, 1.952]} rotation={[Math.PI, 0, Math.PI]}>
        <group position={[-0.021, 0.098, 0.007]} rotation={[0.03, 0.004, 0.02]}>
          <mesh
            geometry={nodes.Cube038_1.geometry}
            material={materials["book cover.005"]}
          />
          <mesh
            geometry={nodes.Cube038_2.geometry}
            material={materials["stacked paper.005"]}
          />
        </group>
        <group
          position={[-0.001, 0.034, -0.007]}
          rotation={[0.024, 0.297, 0.015]}
        >
          <mesh
            geometry={nodes.Cube039_1.geometry}
            material={materials["book cover.005"]}
          />
          <mesh
            geometry={nodes.Cube039_2.geometry}
            material={materials["stacked paper.005"]}
          />
        </group>
        <group
          position={[0.013, 0.009, -0.013]}
          rotation={[0.008, 0.059, 0.003]}
        >
          <mesh
            geometry={nodes.Cube040_1.geometry}
            material={materials["book cover.005"]}
          />
          <mesh
            geometry={nodes.Cube040_2.geometry}
            material={materials["stacked paper.005"]}
          />
        </group>
        <group
          position={[-0.015, 0.077, 0.002]}
          rotation={[0.026, 0.24, 0.022]}
        >
          <mesh
            geometry={nodes.Cube041_1.geometry}
            material={materials["book cover.005"]}
          />
          <mesh
            geometry={nodes.Cube041_2.geometry}
            material={materials["stacked paper.005"]}
          />
        </group>
        <group position={[0.017, 0, -0.017]} rotation={[0.007, 0.144, 0.03]}>
          <mesh
            geometry={nodes.Cube042_1.geometry}
            material={materials["book cover.005"]}
          />
          <mesh
            geometry={nodes.Cube042_2.geometry}
            material={materials["stacked paper.005"]}
          />
        </group>
        <group position={[-0.011, 0.055, 0]} rotation={[0.029, 0.094, 0.018]}>
          <mesh
            geometry={nodes.Cube043_1.geometry}
            material={materials["book cover.005"]}
          />
          <mesh
            geometry={nodes.Cube043_2.geometry}
            material={materials["stacked paper.005"]}
          />
        </group>
        <group
          position={[0.008, 0.022, -0.028]}
          rotation={[0.023, -0.076, 0.01]}
        >
          <mesh
            geometry={nodes.Cube044_1.geometry}
            material={materials["book cover.005"]}
          />
          <mesh
            geometry={nodes.Cube044_2.geometry}
            material={materials["stacked paper.005"]}
          />
        </group>
      </group>
      <group position={[-2.324, 1.424, 0.215]} rotation={[Math.PI, 0, Math.PI]}>
        <group
          position={[-0.015, 0.104, 0.001]}
          rotation={[1.571, -0.102, -1.571]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube045_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube045_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.143, 0.103, -0.006]}
          rotation={[1.571, -0.2, -1.569]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube045_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube045_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.267, 0.099, -0.003]}
          rotation={[1.57, -0.217, -1.574]}
        >
          <mesh
            geometry={nodes.Cube045_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube045_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.063, 0.12, -0.005]}
          rotation={[1.57, -0.108, -1.57]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube046_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube046_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.19, 0.12, -0.005]}
          rotation={[1.572, -0.206, -1.567]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube046_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube046_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.311, 0.114, -0.005]}
          rotation={[1.57, -0.22, -1.575]}
        >
          <mesh
            geometry={nodes.Cube046_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube046_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.045, 0.123, -0.008]}
          rotation={[1.572, -0.106, -1.569]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube047_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube047_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.172, 0.122, -0.006]}
          rotation={[1.569, -0.205, -1.569]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube047_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube047_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.294, 0.116, -0.002]}
          rotation={[1.569, -0.22, -1.575]}
        >
          <mesh
            geometry={nodes.Cube047_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube047_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.033, 0.105, 0.002]}
          rotation={[1.571, -0.106, -1.569]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube048_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube048_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.161, 0.104, -0.011]}
          rotation={[1.571, -0.204, -1.569]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube048_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube048_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.283, 0.1, 0.009]}
          rotation={[1.57, -0.218, -1.573]}
        >
          <mesh
            geometry={nodes.Cube048_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube048_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.092, 0.091, -0.004]}
          rotation={[1.571, -0.152, -1.569]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube049_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube049_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.219, 0.091, -0.002]}
          rotation={[1.571, -0.214, -1.569]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube049_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube049_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.349, 0.085, 0.008]}
          rotation={[1.57, -0.323, -1.575]}
        >
          <mesh
            geometry={nodes.Cube049_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube049_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.108, 0.123, -0.006]}
          rotation={[1.571, -0.201, -1.568]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube050_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube050_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.23, 0.123, -0.009]}
          rotation={[1.57, -0.214, -1.572]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube050_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube050_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.365, 0.111, -0.008]}
          rotation={[1.571, -0.427, -1.572]}
        >
          <mesh
            geometry={nodes.Cube050_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube050_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.126, 0.119, -0.007]}
          rotation={[1.571, -0.201, -1.569]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube051_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube051_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.248, 0.118, -0.005]}
          rotation={[1.57, -0.215, -1.573]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube051_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube051_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
        <group
          position={[-0.388, 0.106, -0.007]}
          rotation={[1.573, -0.45, -1.571]}
        >
          <mesh
            geometry={nodes.Cube051_1.geometry}
            material={materials["book cover.006"]}
          />
          <mesh
            geometry={nodes.Cube051_2.geometry}
            material={materials["stacked paper.006"]}
          />
        </group>
      </group>
      <group position={[-0.491, 0.972, 0.216]} rotation={[Math.PI, 0, Math.PI]}>
        <group
          position={[0.013, 0.118, 0.005]}
          rotation={[1.569, 0.068, -1.571]}
        >
          <mesh
            geometry={nodes.Cube055_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube055_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
        <group
          position={[0.095, 0.122, -0.005]}
          rotation={[1.566, 0.186, -1.57]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube055_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube055_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
        <group
          position={[0.206, 0.111, -0.003]}
          rotation={[1.562, 0.462, -1.567]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube055_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube055_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
        <group
          position={[0.077, 0.12, 0]}
          rotation={[1.571, 0.183, -1.571]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube056_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube056_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
        <group
          position={[0.186, 0.113, -0.004]}
          rotation={[1.568, 0.461, -1.57]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube056_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube056_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
        <group
          position={[0.116, 0.104, -0.009]}
          rotation={[1.572, 0.212, -1.571]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube052_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube052_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
        <group
          position={[0.054, 0.123, -0.004]}
          rotation={[1.571, 0.18, -1.569]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube054_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube054_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
        <group
          position={[0.155, 0.116, 0]}
          rotation={[1.571, 0.425, -1.571]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube054_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube054_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
        <group
          position={[0.037, 0.119, 0.002]}
          rotation={[1.57, 0.175, -1.569]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube053_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube053_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
      </group>
      <group position={[0.299, 1.424, 0.212]}>
        <group
          position={[0.206, 0.111, -0.003]}
          rotation={[1.562, 0.462, -1.567]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube055_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube055_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
        <group
          position={[0.095, 0.122, -0.005]}
          rotation={[1.566, 0.186, -1.57]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube055_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube055_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
        <group
          position={[0.013, 0.118, 0.005]}
          rotation={[1.569, 0.068, -1.571]}
        >
          <mesh
            geometry={nodes.Cube055_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube055_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
        <group
          position={[0.186, 0.113, -0.004]}
          rotation={[1.568, 0.461, -1.57]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube056_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube056_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
        <group
          position={[0.077, 0.12, 0]}
          rotation={[1.571, 0.183, -1.571]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube056_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube056_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
        <group
          position={[0.116, 0.104, -0.009]}
          rotation={[1.572, 0.212, -1.571]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube052_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube052_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
        <group
          position={[0.155, 0.116, 0]}
          rotation={[1.571, 0.425, -1.571]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube054_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube054_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
        <group
          position={[0.054, 0.123, -0.004]}
          rotation={[1.571, 0.18, -1.569]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube054_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube054_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
        <group
          position={[0.037, 0.119, 0.002]}
          rotation={[1.57, 0.175, -1.569]}
          scale={1.045}
        >
          <mesh
            geometry={nodes.Cube053_1.geometry}
            material={materials["book cover.007"]}
          />
          <mesh
            geometry={nodes.Cube053_2.geometry}
            material={materials["stacked paper.007"]}
          />
        </group>
      </group>
      <group position={[1.903, 0.972, 0.233]} rotation={[Math.PI, 0, Math.PI]}>
        <group
          position={[-0.003, 0.045, -0.013]}
          rotation={[-0.003, -0.115, 0.008]}
        >
          <mesh
            geometry={nodes.Cube057_1.geometry}
            material={materials["book cover.008"]}
          />
          <mesh
            geometry={nodes.Cube057_2.geometry}
            material={materials["stacked paper.008"]}
          />
        </group>
        <group
          position={[-0.007, 0.064, -0.016]}
          rotation={[-0.003, -0.044, 0.008]}
        >
          <mesh
            geometry={nodes.Cube058_1.geometry}
            material={materials["book cover.008"]}
          />
          <mesh
            geometry={nodes.Cube058_2.geometry}
            material={materials["stacked paper.008"]}
          />
        </group>
        <group position={[0.006, 0.006, -0.022]} rotation={[0, 0.343, 0.004]}>
          <mesh
            geometry={nodes.Cube059_1.geometry}
            material={materials["book cover.008"]}
          />
          <mesh
            geometry={nodes.Cube059_2.geometry}
            material={materials["stacked paper.008"]}
          />
        </group>
        <group position={[0, 0.024, -0.013]} rotation={[-0.004, 0.058, 0.008]}>
          <mesh
            geometry={nodes.Cube060_1.geometry}
            material={materials["book cover.008"]}
          />
          <mesh
            geometry={nodes.Cube060_2.geometry}
            material={materials["stacked paper.008"]}
          />
        </group>
      </group>
      <group
        position={[-1.133, 0.9, 1.902]}
        rotation={[Math.PI, -1.195, Math.PI]}
      >
        <group
          position={[-0.018, 0.024, 0.084]}
          rotation={[0.361, 0.785, 2.881]}
        >
          <mesh
            geometry={nodes.Plane014.geometry}
            material={materials.BlackMatteColor}
          />
          <mesh
            geometry={nodes.Plane014_1.geometry}
            material={materials.MirrorShader}
          />
        </group>
        <group
          position={[-0.211, 0.002, 0.15]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.362, 0.896, 0.385]}
        >
          <mesh
            geometry={nodes.Cylinder001.geometry}
            material={materials.PenColor01}
          />
          <mesh
            geometry={nodes.Cylinder001_1.geometry}
            material={materials.PenColor02}
          />
        </group>
        <group
          position={[-0.019, 0.032, 0.082]}
          rotation={[2.748, -0.779, 2.858]}
        >
          <mesh
            geometry={nodes.Plane015.geometry}
            material={materials.BlackMatteColor}
          />
          <mesh
            geometry={nodes.Plane015_1.geometry}
            material={materials.MirrorShader}
          />
          <mesh
            geometry={nodes.Plane015_2.geometry}
            material={materials.PhotoDisplay}
          />
        </group>
      </group>
      <group position={[-1.321, 0.9, 2.225]} rotation={[Math.PI, 0, Math.PI]}>
        <group
          position={[0.024, 0.001, -0.023]}
          rotation={[0.909, -0.679, 0.642]}
          scale={0.01}
        >
          <mesh
            geometry={nodes.Cylinder002.geometry}
            material={materials["PLASTIC BLACK"]}
          />
          <mesh
            geometry={nodes.Cylinder002_1.geometry}
            material={materials.metal}
          />
        </group>
        <group
          position={[0.009, 0.076, 0.029]}
          rotation={[0.162, 0.048, 0.022]}
          scale={0.01}
        >
          <mesh
            geometry={nodes.Cylinder003.geometry}
            material={materials["METAL CHROME"]}
          />
          <mesh
            geometry={nodes.Cylinder003_1.geometry}
            material={materials["metalic blue.001"]}
          />
        </group>
        <group
          position={[0.018, 0.062, 0.014]}
          rotation={[-2.815, -0.561, 0.293]}
          scale={0.135}
        >
          <mesh
            geometry={nodes.Cube061_1.geometry}
            material={materials["PLASTIC BLACK"]}
          />
          <mesh
            geometry={nodes.Cube061_2.geometry}
            material={materials["GREEN MARKER"]}
          />
        </group>
        <group
          position={[0.025, 0.043, -0.003]}
          rotation={[-1.072, -1.385, -1.051]}
          scale={0.135}
        >
          <mesh
            geometry={nodes.Cube062_1.geometry}
            material={materials["PLASTIC BLACK"]}
          />
          <mesh
            geometry={nodes.Cube062_2.geometry}
            material={materials["yelow marker"]}
          />
        </group>
        <group
          position={[-0.011, 0.005, 0.011]}
          rotation={[0.267, 0.05, -0.076]}
          scale={0.004}
        >
          <mesh
            geometry={nodes.Cone.geometry}
            material={materials["wood pencil"]}
          />
          <mesh geometry={nodes.Cone_1.geometry} material={materials.granite} />
          <mesh
            geometry={nodes.Cone_2.geometry}
            material={materials["pencil paint"]}
          />
        </group>
        <group
          position={[-0.023, 0.004, 0.011]}
          rotation={[-0.54, -0.17, -0.412]}
          scale={0.004}
        >
          <mesh
            geometry={nodes.Cone002.geometry}
            material={materials["wood pencil"]}
          />
          <mesh
            geometry={nodes.Cone002_1.geometry}
            material={materials.granite}
          />
          <mesh
            geometry={nodes.Cone002_2.geometry}
            material={materials["pencil paint"]}
          />
        </group>
        <mesh
          geometry={nodes.pengolder.geometry}
          material={materials["metalic blue"]}
          scale={0.038}
        />
        <group
          position={[-0.034, 0.154, -0.048]}
          rotation={[0.024, -0.964, 1.927]}
          scale={0.156}
        >
          <mesh
            geometry={nodes.Plane009.geometry}
            material={materials.ruller}
          />
          <mesh
            geometry={nodes.Plane009_1.geometry}
            material={materials["plastic yelow"]}
          />
        </group>
        <group
          position={[0, 0.064, 0.024]}
          rotation={[1.653, -0.011, 3.018]}
          scale={0.02}
        >
          <mesh
            geometry={nodes.Circle003.geometry}
            material={materials.metal}
          />
          <mesh
            geometry={nodes.Circle003_1.geometry}
            material={materials["plastic grey"]}
          />
          <mesh
            geometry={nodes.Circle003_2.geometry}
            material={materials["PLASTIC BLACK"]}
          />
        </group>
      </group>
      <group
        position={[-0.643, 0.9, 1.859]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={-0.037}
      >
        <group
          position={[0, -0.225, 0]}
          rotation={[-2.222, 0.536, 1.02]}
          scale={-0.204}
        >
          <mesh
            geometry={nodes.Circle000.geometry}
            material={materials.Black}
          />
          <mesh
            geometry={nodes.Circle000_1.geometry}
            material={materials["Gold_Plume.001"]}
          />
          <mesh
            geometry={nodes.Circle000_2.geometry}
            material={materials["Blanc_Plume.001"]}
          />
          <mesh
            geometry={nodes.Circle000_3.geometry}
            material={materials["Gols_Plume.001"]}
          />
        </group>
      </group>
      <group
        position={[-0.999, 0.9, 2.346]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.242}
      >
        <group scale={4.127}>
          <mesh
            geometry={nodes.Cylinder004.geometry}
            material={materials["pen_glass 01"]}
          />
          <mesh
            geometry={nodes.Cylinder004_1.geometry}
            material={materials["pen_glass 02"]}
          />
          <mesh
            geometry={nodes.Cylinder004_2.geometry}
            material={materials.pen_metal}
          />
          <mesh
            geometry={nodes.Cylinder004_3.geometry}
            material={materials["pen_yellow plastic"]}
          />
          <mesh
            geometry={nodes.Cylinder004_4.geometry}
            material={materials["pen_green plastic"]}
          />
          <mesh
            geometry={nodes.Cylinder004_5.geometry}
            material={materials["pen_pencil body"]}
          />
          <mesh
            geometry={nodes.Cylinder004_6.geometry}
            material={materials["pen_pencil eraser"]}
          />
          <mesh
            geometry={nodes.Cylinder004_7.geometry}
            material={materials["pen_pencil metal"]}
          />
          <mesh
            geometry={nodes.Cylinder004_8.geometry}
            material={materials.pen_wood}
          />
          <mesh
            geometry={nodes.Cylinder004_9.geometry}
            material={materials["pen_pencil and marker body"]}
          />
          <mesh
            geometry={nodes.Cylinder004_10.geometry}
            material={materials["pen_marker cup"]}
          />
          <mesh
            geometry={nodes.Cylinder004_11.geometry}
            material={materials["pen_blue plastic"]}
          />
          <mesh
            geometry={nodes.Cylinder004_12.geometry}
            material={materials["pen_white eraser"]}
          />
          <mesh
            geometry={nodes.Cylinder004_13.geometry}
            material={materials.pen_protractor}
          />
          <mesh
            geometry={nodes.Cylinder004_14.geometry}
            material={materials["pen_eraser green"]}
          />
          <mesh
            geometry={nodes.Cylinder004_15.geometry}
            material={materials.pen_note}
          />
        </group>
      </group>
      <group
        position={[3.271, -0.001, 2.811]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.465}
      >
        <mesh
          geometry={nodes.Water_Dispenser001.geometry}
          material={materials["Water Dispenser"]}
          scale={2.153}
        />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.914, 0.038, 0.034]}>
        <mesh
          geometry={nodes.Cube001_1.geometry}
          material={materials.Plastic}
        />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.Light} />
      </group>
      <group scale={3.367}>
        <mesh geometry={nodes.Plane.geometry} material={materials.Plaster} />
        <mesh
          geometry={nodes.Plane_1.geometry}
          material={materials.Transluscent}
        />
        <mesh
          geometry={nodes.Plane_2.geometry}
          material={materials["Lights.001"]}
        />
        <mesh geometry={nodes.Plane_3.geometry} material={materials.Goldd} />
        <mesh geometry={nodes.Plane_4.geometry} material={materials.Tiles} />
        <mesh geometry={nodes.Plane_5.geometry} material={materials.Lights} />
        <mesh
          geometry={nodes.Plane_6.geometry}
          material={materials["Glass.001"]}
        />
        <mesh geometry={nodes.Plane_7.geometry} material={materials.Cover} />
        <mesh geometry={nodes.Plane_8.geometry} material={materials.Reflect} />
        <mesh
          geometry={nodes.Plane_9.geometry}
          material={materials["Ceiling.001"]}
        />
        <mesh geometry={nodes.Plane_10.geometry} material={materials.Ceiling} />
        <mesh
          geometry={nodes.Plane_11.geometry}
          material={materials["Realistic glass with imperfections"]}
        />
        <mesh geometry={nodes.Plane_12.geometry} material={materials.Edge} />
        <mesh geometry={nodes.Plane_13.geometry} material={materials.Back} />
        <mesh geometry={nodes.Plane_14.geometry} material={materials.What} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.914, 0.038, 0.034]}>
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials.Plastic}
        />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={materials["Light.001"]}
        />
        <mesh geometry={nodes.Cube002_3.geometry} material={materials.Plast} />
      </group>
      <group position={[0, 0, 2.05]} scale={[1.5, 0.5, 0.45]}>
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials["Black Wood"]}
        />
        <mesh
          geometry={nodes.Cube_1.geometry}
          material={materials["Wood.001"]}
        />
        <mesh
          geometry={nodes.Cube_2.geometry}
          material={materials["Procedual Marble Granite Black Galaxy"]}
        />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.chrome} />
      </group>
      <group position={[3.414, 0, 1.799]}>
        <mesh
          geometry={nodes.Cube004_1.geometry}
          material={materials["Wood.001"]}
        />
        <mesh geometry={nodes.Cube004_2.geometry} material={materials.chrome} />
        <mesh
          geometry={nodes.Cube004_3.geometry}
          material={materials["Black Edge"]}
        />
      </group>
      <group position={[3.437, 1.001, 1.908]} scale={[0.054, 0.136, 0.054]}>
        <mesh
          geometry={nodes.Cylinder_1.geometry}
          material={materials["Procedural Clay"]}
        />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.Red} />
        <mesh
          geometry={nodes.Cylinder_3.geometry}
          material={materials.CloudWhiet}
        />
        <mesh
          geometry={nodes.Cylinder_4.geometry}
          material={materials.Meroon}
        />
      </group>
      <mesh
        geometry={nodes["southIndianBank-logo"].geometry}
        material={materials["southIndianBank-logo"]}
        position={[3.078, 1.567, 1.064]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.577}
      />
      <mesh
        geometry={nodes["southIndianBank-logo001"].geometry}
        material={materials["southIndianBank-logo"]}
        position={[-0.039, 1.217, 6.566]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={1.681}
      />
      <mesh
        geometry={nodes["southIndianBank-logo002"].geometry}
        material={materials["southIndianBank-logo"]}
        position={[-0.039, 1.217, 6.734]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.681}
      />
      <group position={[-0.364, 0.972, 0.214]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials["Material.002"]}
        />
        <group position={[0.012, 0, 0]}>
          <mesh
            geometry={nodes.Plane002.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Plane002_1.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group position={[0.024, 0, 0]} rotation={[0, 0, Math.PI]} scale={-1}>
          <mesh
            geometry={nodes.Plane003.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Plane003_1.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group position={[0.036, 0, 0]} rotation={[0, 0, Math.PI]} scale={-1}>
          <mesh
            geometry={nodes.Plane004.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Plane004_1.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group position={[0.048, 0, 0]}>
          <mesh
            geometry={nodes.Plane005.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Plane005_1.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group position={[0.06, 0, 0]}>
          <mesh
            geometry={nodes.Plane006.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Plane006_1.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group position={[0.072, 0, 0]} rotation={[0, 0, Math.PI]} scale={-1}>
          <mesh
            geometry={nodes.Plane007.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Plane007_1.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <group position={[0.084, 0, 0]}>
          <mesh
            geometry={nodes.Plane008.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            geometry={nodes.Plane008_1.geometry}
            material={materials["Material.002"]}
          />
        </group>
      </group>
      <group
        position={[-0.28, 0.9, 1.906]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.001}
      >
        <mesh geometry={nodes.Mesh.geometry} material={nodes.Mesh.material} />
        <mesh
          geometry={nodes.Mesh_1.geometry}
          material={materials.prop_laptop_lenovo_screen}
        />
      </group>
      <group
        position={[0.873, 0.9, 2.403]}
        rotation={[Math.PI, -0.371, Math.PI]}
      >
        <mesh
          geometry={nodes.Cube063_1.geometry}
          material={materials["black plastic"]}
        />
        <mesh
          geometry={nodes.Cube063_2.geometry}
          material={materials["silver plastic"]}
        />
        <mesh
          geometry={nodes.Cube063_3.geometry}
          material={materials["silver metal"]}
        />
        <mesh
          geometry={nodes.Cube063_4.geometry}
          material={materials.emision}
        />
      </group>
      <mesh
        geometry={nodes.plate003.geometry}
        material={materials["porcelain white.003"]}
        position={[-0.996, 0.9, 2.207]}
        rotation={[Math.PI, 0, Math.PI]}
      >
        <mesh
          geometry={nodes.coffee_bean015.geometry}
          material={materials["coffee bean"]}
          position={[-0.03, 0.007, 0.004]}
          rotation={[-2.949, 1.547, 2.974]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean016.geometry}
          material={materials["coffee bean"]}
          position={[-0.036, 0.008, -0.004]}
          rotation={[-3.063, -0.66, -3.101]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean019.geometry}
          material={materials["coffee bean"]}
          position={[-0.029, 0.01, 0.027]}
          rotation={[2, 0.2, -1.4]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean032.geometry}
          material={materials["coffee bean"]}
          position={[-0.011, 0.008, 0.016]}
          rotation={[-2.734, -1.429, -1.65]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean033.geometry}
          material={materials["coffee bean"]}
          position={[-0.036, 0.008, 0.017]}
          rotation={[-0.05, 0.147, 2.787]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean040.geometry}
          material={materials["coffee bean"]}
          position={[-0.029, 0.007, -0.008]}
          rotation={[2.916, 1.191, 0.199]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean054.geometry}
          material={materials["coffee bean"]}
          position={[-0.024, 0.009, 0.022]}
          rotation={[1.151, 0.578, -0.512]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean063.geometry}
          material={materials["coffee bean"]}
          position={[-0.048, 0.012, 0.006]}
          rotation={[-2.793, -0.718, 0.701]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean067.geometry}
          material={materials["coffee bean"]}
          position={[-0.041, 0.011, 0.023]}
          rotation={[-2.421, -1.044, 1.025]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean068.geometry}
          material={materials["coffee bean"]}
          position={[-0.019, 0.007, 0.018]}
          rotation={[-0.03, 0.967, -3.081]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean069.geometry}
          material={materials["coffee bean"]}
          position={[-0.036, 0.012, 0.015]}
          rotation={[0.735, 0.996, 2.22]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean075.geometry}
          material={materials["coffee bean"]}
          position={[-0.028, 0.009, 0.019]}
          rotation={[-0.828, -1.088, -1.842]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean080.geometry}
          material={materials["coffee bean"]}
          position={[-0.022, 0.008, 0.004]}
          rotation={[-2.933, -0.876, -2.968]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean082.geometry}
          material={materials["coffee bean"]}
          position={[-0.025, 0.012, 0.014]}
          rotation={[3.1, -1.394, -0.643]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean097.geometry}
          material={materials["coffee bean"]}
          position={[-0.042, 0.011, 0.014]}
          rotation={[-2.948, -0.34, -2.678]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean099.geometry}
          material={materials["coffee bean"]}
          position={[-0.036, 0.009, 0.01]}
          rotation={[-0.223, -1.145, 1.449]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean104.geometry}
          material={materials["coffee bean"]}
          position={[-0.034, 0.011, 0.025]}
          rotation={[0.098, 0.134, -1.651]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean112.geometry}
          material={materials["coffee bean"]}
          position={[-0.034, 0.007, -0.011]}
          rotation={[-0.171, -1.064, -0.185]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean113.geometry}
          material={materials["coffee bean"]}
          position={[-0.033, 0.011, 0.002]}
          rotation={[0.265, 1.203, -0.151]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean133.geometry}
          material={materials["coffee bean"]}
          position={[-0.039, 0.009, 0.006]}
          rotation={[-1.561, -0.961, -2.652]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean138.geometry}
          material={materials["coffee bean"]}
          position={[-0.03, 0.007, 0.013]}
          rotation={[3.1, 0.018, -0.047]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean141.geometry}
          material={materials["coffee bean"]}
          position={[-0.017, 0.008, 0.011]}
          rotation={[0.279, 1.446, -1.388]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean147.geometry}
          material={materials["coffee bean"]}
          position={[-0.042, 0.009, 0.001]}
          rotation={[1.183, 1.122, 1.864]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean161.geometry}
          material={materials["coffee bean"]}
          position={[-0.031, 0.011, 0.01]}
          rotation={[3.106, 0.615, -2.18]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean163.geometry}
          material={materials["coffee bean"]}
          position={[-0.027, 0.008, -0.002]}
          rotation={[0.528, 0.078, 2.889]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.coffee_bean171.geometry}
          material={materials["coffee bean"]}
          position={[-0.025, 0.008, 0.01]}
          rotation={[0.175, 0.56, -1.606]}
          scale={1.43}
        />
        <mesh
          geometry={nodes.MUG003.geometry}
          material={materials["porcelain white.004"]}
          position={[0.003, 0.005, -0.01]}
          rotation={[0, -1.571, 0]}
        >
          <mesh
            geometry={nodes.Circle002.geometry}
            material={materials["coffee.002"]}
            position={[0, 0.027, 0]}
            scale={0.904}
          />
        </mesh>
        <mesh
          geometry={nodes.spoon001.geometry}
          material={materials["Iron Touched.001"]}
          position={[0.027, 0.009, 0.026]}
          rotation={[-2.517, 1.393, 2.49]}
          scale={0.759}
        />
      </mesh>
      <mesh
        geometry={nodes.Executive_office_chair.geometry}
        material={materials["Material.003"]}
        position={[-0.306, 0, 1.414]}
      />
      <group position={[-0.977, 0, 3.175]} rotation={[0, 1.571, 0]}>
        <mesh
          geometry={nodes.Black_leather_chair_1.geometry}
          material={materials["Chair seam "]}
        />
        <mesh
          geometry={nodes.Black_leather_chair_2.geometry}
          material={materials["Chair black plastic "]}
        />
        <mesh
          geometry={nodes.Black_leather_chair_3.geometry}
          material={materials["Chair Black leather "]}
        />
        <mesh
          geometry={nodes.Black_leather_chair_4.geometry}
          material={materials["Chair chrome metal"]}
        />
      </group>
      <group position={[0.851, 0, 3.175]} rotation={[0, -1.571, 0]}>
        <mesh
          geometry={nodes.Black_leather_chair001_1.geometry}
          material={materials["Chair seam "]}
        />
        <mesh
          geometry={nodes.Black_leather_chair001_2.geometry}
          material={materials["Chair black plastic "]}
        />
        <mesh
          geometry={nodes.Black_leather_chair001_3.geometry}
          material={materials["Chair Black leather "]}
        />
        <mesh
          geometry={nodes.Black_leather_chair001_4.geometry}
          material={materials["Chair chrome metal"]}
        />
      </group>
      <mesh
        geometry={nodes.Shelves1001.geometry}
        material={materials.Shelves_material}
      />
      <mesh
        geometry={nodes.Shelves1001_1.geometry}
        material={materials.Metal}
      />
      <mesh
        geometry={nodes.Shelves1001_2.geometry}
        material={materials.Silver}
      />
      <mesh
        geometry={nodes.Shelves1001_3.geometry}
        material={materials.Platinum}
      />
      <mesh
        geometry={nodes.Shelves1001_4.geometry}
        material={materials["Cover.001"]}
      />
      <mesh
        geometry={nodes.Shelves1001_5.geometry}
        material={materials.Lights}
      />
    </group>
  );
}

useGLTF.preload("/bg.gltf");
