/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/african afro.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Vector3 } from 'three'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/african afro.gltf')
  return (
    <group    position={0,0,-0.5} {...props} dispose={null}>
      <mesh    geometry={nodes.Cylinder.geometry} material={materials['Material.011']} />
      <mesh  geometry={nodes.Plane.geometry} material={materials['Material.010']} scale={0.841} />
      <mesh  geometry={nodes.Plane001.geometry} material={materials['Material.009']} />
      <mesh  geometry={nodes.Plane004.geometry} material={materials['Material.006']} />
      <mesh  geometry={nodes.Plane008.geometry} material={materials['Material.005']} />
      <mesh  geometry={nodes.Sphere002.geometry} material={materials['Material.003']} position={[0, 0.416, 0]} scale={0.42} />
    </group>
  )
}

useGLTF.preload('/african afro.gltf')
